fix for the Ipython Notebook and EarthLocation representation warning/error #4542  (ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all())
The error message explains it pretty well:
ValueError: The truth value of an array with more than one element is ambiguous. 
Use a.any() or a.all()
What should bool(np.array([False, False, True])) return? You can make several plausible arguments:
(1) True, because bool(np.array(x)) should return the same as bool(list(x)), and non-empty lists are truelike;
(2) True, because at least one element is True;
(3) False, because not all elements are True;
and that's not even considering the complexity of the N-d case.
So, since "the truth value of an array with more than one element is ambiguous", you should use .any() or .all(), for example:
so the fix is to use np.all(array([ True,  True, False], dtype=bool))
or 
np.any(array([ True,  True, False], dtype=bool))